# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.get_timers200_response_worker import GetTimers200ResponseWorker

class TestGetTimers200ResponseWorker(unittest.TestCase):
    """GetTimers200ResponseWorker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTimers200ResponseWorker:
        """Test GetTimers200ResponseWorker
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTimers200ResponseWorker`
        """
        model = GetTimers200ResponseWorker()
        if include_optional:
            return GetTimers200ResponseWorker(
                id = 56,
                count = 56
            )
        else:
            return GetTimers200ResponseWorker(
        )
        """

    def testGetTimers200ResponseWorker(self):
        """Test GetTimers200ResponseWorker"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
