# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kong_admin_client.api.key_sets_api import KeySetsApi


class TestKeySetsApi(unittest.TestCase):
    """KeySetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeySetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_key_set(self) -> None:
        """Test case for create_key_set

        Create a new Key-set
        """
        pass

    def test_delete_key_set(self) -> None:
        """Test case for delete_key_set

        Delete a Key-set
        """
        pass

    def test_get_key_set(self) -> None:
        """Test case for get_key_set

        Fetch a Key-set
        """
        pass

    def test_list_key_set(self) -> None:
        """Test case for list_key_set

        List all Key-sets
        """
        pass

    def test_update_key_set(self) -> None:
        """Test case for update_key_set

        Update a Key-set
        """
        pass

    def test_upsert_key_set(self) -> None:
        """Test case for upsert_key_set

        Update a Key-set
        """
        pass


if __name__ == '__main__':
    unittest.main()
