# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kong_admin_client.api.acls_api import ACLsApi


class TestACLsApi(unittest.TestCase):
    """ACLsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ACLsApi()

    def tearDown(self) -> None:
        pass

    def test_create_acl_for_consumer(self) -> None:
        """Test case for create_acl_for_consumer

        Create a new ACL associated with a Consumer
        """
        pass

    def test_list_acls_for_consumer(self) -> None:
        """Test case for list_acls_for_consumer

        List all ACLs associated with a consumer
        """
        pass


if __name__ == '__main__':
    unittest.main()
