# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kong_admin_client.api.vaults_api import VaultsApi


class TestVaultsApi(unittest.TestCase):
    """VaultsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VaultsApi()

    def tearDown(self) -> None:
        pass

    def test_create_vault(self) -> None:
        """Test case for create_vault

        Create a new Vault
        """
        pass

    def test_delete_vault(self) -> None:
        """Test case for delete_vault

        Delete a Vault
        """
        pass

    def test_get_vault(self) -> None:
        """Test case for get_vault

        Fetch a Vault
        """
        pass

    def test_list_vault(self) -> None:
        """Test case for list_vault

        List all Vaults
        """
        pass

    def test_update_vault(self) -> None:
        """Test case for update_vault

        Update a Vault
        """
        pass

    def test_upsert_vault(self) -> None:
        """Test case for upsert_vault

        Upsert a Vault
        """
        pass


if __name__ == '__main__':
    unittest.main()
