# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kong_admin_client.api.ca_certificates_api import CACertificatesApi


class TestCACertificatesApi(unittest.TestCase):
    """CACertificatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CACertificatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_ca_certificate(self) -> None:
        """Test case for create_ca_certificate

        Create a new CA certificate
        """
        pass

    def test_delete_ca_certificate(self) -> None:
        """Test case for delete_ca_certificate

        Delete a CA Certificate
        """
        pass

    def test_get_ca_certificate(self) -> None:
        """Test case for get_ca_certificate

        Fetch a CA certificate
        """
        pass

    def test_list_ca_certificate(self) -> None:
        """Test case for list_ca_certificate

        List all CA certificates
        """
        pass

    def test_update_ca_certificate(self) -> None:
        """Test case for update_ca_certificate

        Update a CA Certificate
        """
        pass

    def test_updatet_ca_certificate(self) -> None:
        """Test case for updatet_ca_certificate

        Update a CA Certificate
        """
        pass


if __name__ == '__main__':
    unittest.main()
