# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.get_sni_with_certificate200_response_data_inner_certificate import GetSniWithCertificate200ResponseDataInnerCertificate

class TestGetSniWithCertificate200ResponseDataInnerCertificate(unittest.TestCase):
    """GetSniWithCertificate200ResponseDataInnerCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSniWithCertificate200ResponseDataInnerCertificate:
        """Test GetSniWithCertificate200ResponseDataInnerCertificate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSniWithCertificate200ResponseDataInnerCertificate`
        """
        model = GetSniWithCertificate200ResponseDataInnerCertificate()
        if include_optional:
            return GetSniWithCertificate200ResponseDataInnerCertificate(
                id = '2e013e8-7623-4494-a347-6d29108ff68b'
            )
        else:
            return GetSniWithCertificate200ResponseDataInnerCertificate(
        )
        """

    def testGetSniWithCertificate200ResponseDataInnerCertificate(self):
        """Test GetSniWithCertificate200ResponseDataInnerCertificate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
