# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kong_admin_client.api.consumers_api import ConsumersApi


class TestConsumersApi(unittest.TestCase):
    """ConsumersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConsumersApi()

    def tearDown(self) -> None:
        pass

    def test_create_consumer(self) -> None:
        """Test case for create_consumer

        Create a new Consumer
        """
        pass

    def test_delete_consumer(self) -> None:
        """Test case for delete_consumer

        Delete a Consumer
        """
        pass

    def test_get_consumer(self) -> None:
        """Test case for get_consumer

        Fetch a Consumer
        """
        pass

    def test_list_consumer(self) -> None:
        """Test case for list_consumer

        List all Consumers
        """
        pass

    def test_update_consumer(self) -> None:
        """Test case for update_consumer

        Update a Consumer
        """
        pass

    def test_upsert_consumer(self) -> None:
        """Test case for upsert_consumer

        Update a Consumer
        """
        pass


if __name__ == '__main__':
    unittest.main()
