# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.get_sni_with_certificate200_response import GetSniWithCertificate200Response

class TestGetSniWithCertificate200Response(unittest.TestCase):
    """GetSniWithCertificate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSniWithCertificate200Response:
        """Test GetSniWithCertificate200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSniWithCertificate200Response`
        """
        model = GetSniWithCertificate200Response()
        if include_optional:
            return GetSniWithCertificate200Response(
                data = [
                    kong_admin_client.models.get_sni_with_certificate_200_response_data_inner.get_sni_with_certificate_200_response_data_inner(
                        id = '147f5ef0-1ed6-4711-b77f-489262f8bff7', 
                        name = 'my-sni', 
                        created_at = 1422386534, 
                        tags = [
                            ''
                            ], 
                        certificate = kong_admin_client.models.get_sni_with_certificate_200_response_data_inner_certificate.get_sni_with_certificate_200_response_data_inner_certificate(
                            id = '2e013e8-7623-4494-a347-6d29108ff68b', ), )
                    ],
                next = 'http://localhost:8001/snis?offset=6378122c-a0a1-438d-a5c6-efabae9fb969'
            )
        else:
            return GetSniWithCertificate200Response(
        )
        """

    def testGetSniWithCertificate200Response(self):
        """Test GetSniWithCertificate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
