# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.vault import Vault

class TestVault(unittest.TestCase):
    """Vault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Vault:
        """Test Vault
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vault`
        """
        model = Vault()
        if include_optional:
            return Vault(
                config = kong_admin_client.models.vault_config.Vault_config(
                    prefix = 'vaults.config.resurrect_ttl', ),
                created_at = 1422386534,
                description = 'This vault is used to retrieve redis database access credentials',
                id = 'B2A30E8F-C542-49CF-8015-FB674987D1A5',
                name = 'env',
                prefix = 'env',
                tags = [
                    'database-credentials'
                    ],
                updated_at = 1422386534
            )
        else:
            return Vault(
        )
        """

    def testVault(self):
        """Test Vault"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
