# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.list_key200_response import ListKey200Response

class TestListKey200Response(unittest.TestCase):
    """ListKey200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListKey200Response:
        """Test ListKey200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListKey200Response`
        """
        model = ListKey200Response()
        if include_optional:
            return ListKey200Response(
                data = [
                    {"id":"d958f66b-8e99-44d2-b0b4-edd5bbf24658","jwk":"{\"alg\":\"RSA\",  \"kid\": \"42\",  ...}","kid":"42","name":"a-key","pem":{"private_key":"-----BEGIN","public_key":"-----BEGIN"},"set":{"id":"b86b331c-dcd0-4b3e-97ce-47c5a9543031"}}
                    ],
                offset = ''
            )
        else:
            return ListKey200Response(
        )
        """

    def testListKey200Response(self):
        """Test ListKey200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
