# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.create_key_request import CreateKeyRequest

class TestCreateKeyRequest(unittest.TestCase):
    """CreateKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateKeyRequest:
        """Test CreateKeyRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateKeyRequest`
        """
        model = CreateKeyRequest()
        if include_optional:
            return CreateKeyRequest(
                set = kong_admin_client.models.create_key_request_set.create_key_request_set(
                    id = '', ),
                name = 'my-key',
                kid = '42',
                jwk = '{\"alg\":\"RSA\",  \"kid\": \"42\",  ...}',
                pem = kong_admin_client.models.create_key_request_pem.create_key_request_pem(
                    private_key = 'private_key": "-----BEGIN', 
                    public_key = 'public_key": "-----BEGIN', ),
                tags = [
                    ''
                    ]
            )
        else:
            return CreateKeyRequest(
                kid = '42',
        )
        """

    def testCreateKeyRequest(self):
        """Test CreateKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
