# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.get_status200_response import GetStatus200Response

class TestGetStatus200Response(unittest.TestCase):
    """GetStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStatus200Response:
        """Test GetStatus200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStatus200Response`
        """
        model = GetStatus200Response()
        if include_optional:
            return GetStatus200Response(
                memory = kong_admin_client.models.get_status_200_response_memory.get_status_200_response_memory(
                    lua_shared_dicts = kong_admin_client.models.get_status_200_response_memory_lua_shared_dicts.get_status_200_response_memory_lua_shared_dicts(
                        kong_core_db_cache = kong_admin_client.models.get_status_200_response_memory_lua_shared_dicts_kong_core_db_cache.get_status_200_response_memory_lua_shared_dicts_kong_core_db_cache(
                            capacity = '128.00 MiB', 
                            allocated_slabs = '128.00 MiB', ), ), 
                    workers_lua_vms = [
                        kong_admin_client.models.get_status_200_response_memory_workers_lua_vms_inner.get_status_200_response_memory_workers_lua_vms_inner(
                            http_allocated_gc = '', 
                            pid = 18478, )
                        ], ),
                database = kong_admin_client.models.get_status_200_response_database.get_status_200_response_database(
                    reachable = True, ),
                server = kong_admin_client.models.get_status_200_response_server.get_status_200_response_server(
                    connections_reading = 3, 
                    connections_writing = 1, 
                    total_requests = 1, 
                    connections_waiting = 1, 
                    connections_handled = 1, 
                    connections_active = 1, 
                    connections_accepted = 1, )
            )
        else:
            return GetStatus200Response(
        )
        """

    def testGetStatus200Response(self):
        """Test GetStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
