# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.route import Route

class TestRoute(unittest.TestCase):
    """Route unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Route:
        """Test Route
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Route`
        """
        model = Route()
        if include_optional:
            return Route(
                created_at = 56,
                destinations = [
                    kong_admin_client.models.route_destinations_inner.Route_destinations_inner(
                        default = null, )
                    ],
                headers = None,
                hosts = [
                    '"foo.example.com"'
                    ],
                https_redirect_status_code = 56,
                id = '56c4566c-14cc-4132-9011-4139fcbbe50a',
                methods = [
                    ''
                    ],
                name = '',
                path_handling = 'v0',
                paths = [
                    ''
                    ],
                preserve_host = True,
                protocols = [
                    ''
                    ],
                regex_priority = 56,
                request_buffering = True,
                response_buffering = True,
                service = kong_admin_client.models.route_service.Route_service(
                    id = '', ),
                snis = [
                    ''
                    ],
                sources = [
                    kong_admin_client.models.route_destinations_inner.Route_destinations_inner(
                        default = null, )
                    ],
                strip_path = True,
                tags = [
                    ''
                    ],
                updated_at = 56
            )
        else:
            return Route(
        )
        """

    def testRoute(self):
        """Test Route"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
