# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.service import Service

class TestService(unittest.TestCase):
    """Service unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Service:
        """Test Service
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Service`
        """
        model = Service()
        if include_optional:
            return Service(
                ca_certificates = [
                    ''
                    ],
                client_certificate = kong_admin_client.models.service_client_certificate.Service_client_certificate(
                    id = '', ),
                connect_timeout = 56,
                created_at = 1422386534,
                enabled = True,
                host = '',
                id = '',
                name = '',
                path = '',
                port = 56,
                protocol = 'http',
                read_timeout = 56,
                retries = 56,
                tags = [
                    ''
                    ],
                tls_verify = True,
                tls_verify_depth = 56,
                updated_at = 56,
                url = '',
                write_timeout = 56
            )
        else:
            return Service(
        )
        """

    def testService(self):
        """Test Service"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
