# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.get_status200_response_memory_lua_shared_dicts import GetStatus200ResponseMemoryLuaSharedDicts

class TestGetStatus200ResponseMemoryLuaSharedDicts(unittest.TestCase):
    """GetStatus200ResponseMemoryLuaSharedDicts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStatus200ResponseMemoryLuaSharedDicts:
        """Test GetStatus200ResponseMemoryLuaSharedDicts
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStatus200ResponseMemoryLuaSharedDicts`
        """
        model = GetStatus200ResponseMemoryLuaSharedDicts()
        if include_optional:
            return GetStatus200ResponseMemoryLuaSharedDicts(
                kong_core_db_cache = kong_admin_client.models.get_status_200_response_memory_lua_shared_dicts_kong_core_db_cache.get_status_200_response_memory_lua_shared_dicts_kong_core_db_cache(
                    capacity = '128.00 MiB', 
                    allocated_slabs = '128.00 MiB', )
            )
        else:
            return GetStatus200ResponseMemoryLuaSharedDicts(
        )
        """

    def testGetStatus200ResponseMemoryLuaSharedDicts(self):
        """Test GetStatus200ResponseMemoryLuaSharedDicts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
