# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.list_plugins_for_route200_response import ListPluginsForRoute200Response

class TestListPluginsForRoute200Response(unittest.TestCase):
    """ListPluginsForRoute200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPluginsForRoute200Response:
        """Test ListPluginsForRoute200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPluginsForRoute200Response`
        """
        model = ListPluginsForRoute200Response()
        if include_optional:
            return ListPluginsForRoute200Response(
                data = [
                    {"config":{"anonymous":null,"hide_credentials":false,"key_in_body":false,"key_in_header":true,"key_in_query":true,"key_names":["apikey"],"run_on_preflight":true},"enabled":true,"id":"3fd1eea1-885a-4011-b986-289943ff8177","name":"key-auth","protocols":["grpc","grpcs","http","https"]}
                    ],
                offset = ''
            )
        else:
            return ListPluginsForRoute200Response(
        )
        """

    def testListPluginsForRoute200Response(self):
        """Test ListPluginsForRoute200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
