# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.key import Key

class TestKey(unittest.TestCase):
    """Key unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Key:
        """Test Key
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Key`
        """
        model = Key()
        if include_optional:
            return Key(
                created_at = 1422386534,
                id = '24D0DBDA-671C-11ED-BA0B-EF1DCCD3725F',
                jwk = '{\"alg\":\"RSA\",  \"kid\": \"42\",  ...}',
                kid = '"42"',
                name = 'a-key',
                pem = kong_admin_client.models.key_pem.Key_pem(
                    private_key = '"-----BEGIN"', 
                    public_key = '"-----BEGIN"', ),
                set = kong_admin_client.models.key_set.Key_set(
                    id = '46CA83EE-671C-11ED-BFAB-2FE47512C77A', ),
                tags = [
                    ''
                    ],
                updated_at = 1422386534
            )
        else:
            return Key(
        )
        """

    def testKey(self):
        """Test Key"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
