# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.get_timers200_response_stats import GetTimers200ResponseStats

class TestGetTimers200ResponseStats(unittest.TestCase):
    """GetTimers200ResponseStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTimers200ResponseStats:
        """Test GetTimers200ResponseStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTimers200ResponseStats`
        """
        model = GetTimers200ResponseStats()
        if include_optional:
            return GetTimers200ResponseStats(
                sys = kong_admin_client.models.get_timers_200_response_stats_sys.get_timers_200_response_stats_sys(
                    total = 7, 
                    waiting = 7, 
                    runs = 7, 
                    pending = 0, 
                    running = 0, ),
                flamegraph = kong_admin_client.models.get_timers_200_response_stats_flamegraph.get_timers_200_response_stats_flamegraph(
                    pending = '@./kong/init.lua:706:init_worker();@./kong/runloop/handler.lua:1086:before() 0
', 
                    running = '@./kong/init.lua:706:init_worker();@./kong/runloop/handler.lua:1086:before() 0
', 
                    elapsed_time = '@./kong/init.lua:706:init_worker();@./kong/runloop/handler.lua:1086:before() 17
', ),
                timers = kong_admin_client.models.get_timers_200_response_stats_timers.get_timers_200_response_stats_timers(
                    meta = kong_admin_client.models.get_timers_200_response_stats_timers_meta.get_timers_200_response_stats_timers_meta(
                        name = '@/build/luarocks/share/lua/5.1/resty/counter.lua:71:new()', ), )
            )
        else:
            return GetTimers200ResponseStats(
        )
        """

    def testGetTimers200ResponseStats(self):
        """Test GetTimers200ResponseStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
