# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kong_admin_client.models.list_plugins_for_consumer200_response_config import ListPluginsForConsumer200ResponseConfig

class TestListPluginsForConsumer200ResponseConfig(unittest.TestCase):
    """ListPluginsForConsumer200ResponseConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPluginsForConsumer200ResponseConfig:
        """Test ListPluginsForConsumer200ResponseConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPluginsForConsumer200ResponseConfig`
        """
        model = ListPluginsForConsumer200ResponseConfig()
        if include_optional:
            return ListPluginsForConsumer200ResponseConfig(
                hour = 500,
                minute = 500
            )
        else:
            return ListPluginsForConsumer200ResponseConfig(
        )
        """

    def testListPluginsForConsumer200ResponseConfig(self):
        """Test ListPluginsForConsumer200ResponseConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
