# coding: utf-8

"""
    Kong Admin API

    OpenAPI 3.0 spec for Kong Gateway's open source Admin API.  You can know more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com) .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.

    The version of the OpenAPI document: 3.5.0
    Contact: docs@konghq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kong_admin_client.models.filter_chain_filters_inner import FilterChainFiltersInner
from kong_admin_client.models.filter_chain_route import FilterChainRoute
from kong_admin_client.models.filter_chain_service import FilterChainService
from typing import Optional, Set
from typing_extensions import Self

class FilterChain(BaseModel):
    """
    A Filter Chain entity represents a list of one or more WebAssembly filters that will be executed during the HTTP request/response lifecycle.
    """ # noqa: E501
    created_at: Optional[StrictInt] = Field(default=None, description="Unix epoch when the resource was created.")
    enabled: Optional[StrictBool] = Field(default=None, description="Whether the filter chain is applied.")
    filters: Optional[List[FilterChainFiltersInner]] = Field(default=None, description="An array of filter definitions that will be executed in order.")
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = Field(default=None, description="The name of the filter chain.")
    route: Optional[FilterChainRoute] = None
    service: Optional[FilterChainService] = None
    tags: Optional[List[StrictStr]] = Field(default=None, description="An optional set of strings associated with the Filter Chain for grouping and filtering.")
    updated_at: Optional[StrictInt] = Field(default=None, description="Unix epoch when the resource was last updated.")
    __properties: ClassVar[List[str]] = ["created_at", "enabled", "filters", "id", "name", "route", "service", "tags", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FilterChain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item in self.filters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of route
        if self.route:
            _dict['route'] = self.route.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service
        if self.service:
            _dict['service'] = self.service.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FilterChain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "enabled": obj.get("enabled"),
            "filters": [FilterChainFiltersInner.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "route": FilterChainRoute.from_dict(obj["route"]) if obj.get("route") is not None else None,
            "service": FilterChainService.from_dict(obj["service"]) if obj.get("service") is not None else None,
            "tags": obj.get("tags"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


